name: build
on: [push, pull_request]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    name: ${{ matrix.config.distro }}:${{ matrix.config.version }}
    container:
      image: ${{ matrix.config.distro }}:${{ matrix.config.version }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {distro: 'fedora', version: '35'}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        dnf install -y R-devel devscripts-checkbashisms
        Rscript -e 'install.packages("tinytest", repos="https://cran.r-project.org")'

    - name: Check
      env:
        LANG: C.UTF-8
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
      run: |
        R CMD build . && mkdir check

        # with flexiblas
        R CMD check flexiblas_*.tar.gz --no-manual -o check

        # without flexiblas
        mv /lib64/libflexiblas.so.3.1 /lib64/libflexiblas.so.3.1.bkp
        ln -s /lib64/libopenblaso.so.0 /lib64/libflexiblas.so.3.1
        R CMD check flexiblas_*.tar.gz --no-manual -o check

    - name: Upload check results
      if: ${{ failure() }}
      uses: actions/upload-artifact@master
      with:
        name: r-${{ matrix.config.distro }}-${{ matrix.config.version }}-results
        path: check
